name: 'setup-terragrunt tests'

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  terragrunt-versions:
    name: 'Terragrunt Versions'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terragrunt-versions: [0.54.20, 0.57.13]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Terragrunt - ${{ matrix['terragrunt-versions'] }}
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        terragrunt_version: ${{ matrix['terragrunt-versions'] }}

    - name: Validate Terragrunt Version - ${{ matrix['terragrunt-versions'] }}
      run: terragrunt -version | grep ${{ matrix['terragrunt-versions']}}

    - name: Validate Terragrunt Version - ${{ matrix['terragrunt-versions'] }}
      run: terragrunt -version | grep 'terragrunt version v'

  terragrunt-versions-no-wrapper:
    name: 'Terragrunt Versions No Wrapper'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terragrunt-versions: [0.54.20, 0.57.13]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Terragrunt (no wrapper) - ${{ matrix['terragrunt-versions'] }}
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        terragrunt_version: ${{ matrix['terragrunt-versions'] }}
        terragrunt_wrapper: false

    - name: Validate Terragrunt Version - ${{ matrix['terragrunt-versions'] }}
      run: terragrunt -version | grep ${{ matrix['terragrunt-versions']}}

    - name: Validate Terragrunt Version - ${{ matrix['terragrunt-versions'] }}
      run: terragrunt -version | grep 'terragrunt version v'

  terragrunt-arguments:
    name: 'Terragrunt Arguments'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terragrunt-versions: [0.57.13]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Terragrunt
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        terragrunt_version: ${{ matrix['terragrunt-versions'] }}

    - name: Check No Arguments
      run: terragrunt || exit 0

    - name: Check Single Argument
      run: terragrunt help || exit 0

    - name: Check Single Argument Hyphen
      run: terragrunt -help

    - name: Check Single Argument Double Hyphen
      run: terragrunt --help

    - name: Check Single Argument Subcommand
      run: terragrunt hclfmt --terragrunt-check

    - name: Check Multiple Arguments Subcommand
      run: terragrunt hclfmt --terragrunt-check -list=true -no-color

  terragrunt-arguments-no-wrapper:
    name: 'Terragrunt Arguments No Wrapper'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terragrunt-versions: [0.57.13]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Terragrunt
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        terragrunt_wrapper: false
        terragrunt_version: ${{ matrix['terragrunt-versions'] }}

    - name: Check No Arguments
      run: terragrunt || exit 0

    - name: Check Single Argument
      run: terragrunt help || exit 0

    - name: Check Single Argument Hyphen
      run: terragrunt -help

    - name: Check Single Argument Double Hyphen
      run: terragrunt --help

    - name: Check Single Argument Subcommand
      run: terragrunt hclfmt --terragrunt-check

    - name: Check Multiple Arguments Subcommand
      run: terragrunt hclfmt --terragrunt-check -list=true -no-color

